const encoder = new TextEncoder();
const json = (body, status = 200, headers = {}) => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json; charset=UTF-8', ...headers } });
const id = () => crypto.randomUUID();
const now = () => new Date().toISOString();
const b64 = value => btoa(String.fromCharCode(...new Uint8Array(value))).replaceAll('+', '-').replaceAll('/', '_').replaceAll('=', '');
const unb64 = value => Uint8Array.from(atob(value.replaceAll('-', '+').replaceAll('_', '/').padEnd(Math.ceil(value.length / 4) * 4, '=')), char => char.charCodeAt(0));
const sha256 = async value => b64(await crypto.subtle.digest('SHA-256', encoder.encode(value)));
const hmac = async (value, secret) => {
  const key = await crypto.subtle.importKey('raw', encoder.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  return b64(await crypto.subtle.sign('HMAC', key, encoder.encode(value)));
};
const sign = async (payload, env) => { const data = b64(encoder.encode(JSON.stringify(payload))); return `${data}.${await hmac(data, env.AUTH_SECRET)}`; };
const verify = async (token, env) => { const [data, signature] = (token || '').split('.'); if (!data || signature !== await hmac(data, env.AUTH_SECRET)) return null; try { const payload = JSON.parse(new TextDecoder().decode(unb64(data))); return payload.exp > Date.now() ? payload : null; } catch { return null; } };
async function encryptSecret(value, env) {
  if (!env.DATA_ENCRYPTION_KEY) throw new Error('DATA_ENCRYPTION_KEY is not configured.');
  const rawKey = unb64(env.DATA_ENCRYPTION_KEY);
  if (rawKey.byteLength !== 32) throw new Error('DATA_ENCRYPTION_KEY must be a base64url-encoded 32-byte value.');
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const key = await crypto.subtle.importKey('raw', rawKey, { name: 'AES-GCM' }, false, ['encrypt']);
  const ciphertext = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, key, encoder.encode(value));
  return { version: 1, algorithm: 'AES-GCM', iv: b64(iv), ciphertext: b64(ciphertext) };
}
async function decryptSecret(envelope, env) {
  if (!envelope?.iv || !envelope?.ciphertext || !env.DATA_ENCRYPTION_KEY) throw new Error('Encrypted integration credentials are unavailable.');
  const rawKey = unb64(env.DATA_ENCRYPTION_KEY); if (rawKey.byteLength !== 32) throw new Error('DATA_ENCRYPTION_KEY is invalid.');
  const key = await crypto.subtle.importKey('raw', rawKey, { name: 'AES-GCM' }, false, ['decrypt']);
  const plaintext = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: unb64(envelope.iv) }, key, unb64(envelope.ciphertext));
  return new TextDecoder().decode(plaintext);
}
const cookie = (request, name) => Object.fromEntries((request.headers.get('cookie') || '').split(';').filter(Boolean).map(x => x.trim().split('=')))[name];

// Permission checks are deliberately close to the route definitions. Finance-only data must never be returned to a teacher role.
const can = (user, ...roles) => user && roles.includes(user.role);
const isSecurityOwner = user => can(user, 'admin') && Number(user.is_super_admin) === 1;
const secretMatches = async (provided, expected) => {
  if (!provided || !expected) return false;
  const [left,right] = await Promise.all([crypto.subtle.digest('SHA-256', encoder.encode(provided)),crypto.subtle.digest('SHA-256', encoder.encode(expected))]);
  return b64(left) === b64(right);
};
async function currentUser(request, env) {
  const session = await verify(cookie(request, 'legacy_session'), env);
  if (!session) return null;
  const user = await env.DB.prepare('SELECT id,email,name,role,status,is_super_admin FROM users WHERE id=? AND status="active"').bind(session.sub).first();
  // The configured bootstrap administrator is the only account that may be
  // elevated implicitly. This makes the first security-report configuration
  // possible without opening a self-service privilege-escalation route.
  if (user && user.role === 'admin' && Number(user.is_super_admin) !== 1 && env.BOOTSTRAP_ADMIN_EMAIL?.trim().toLowerCase() === user.email.toLowerCase()) {
    await env.DB.prepare('UPDATE users SET is_super_admin=1,updated_at=? WHERE id=?').bind(now(), user.id).run();
    user.is_super_admin = 1;
  }
  return user;
}
async function audit(env, actor, action, entityType, entityId, metadata = {}) {
  await env.DB.prepare('INSERT INTO audit_logs (id,actor_user_id,action,entity_type,entity_id,metadata_json) VALUES (?,?,?,?,?,?)').bind(id(), actor?.id || null, action, entityType, entityId || null, JSON.stringify(metadata)).run();
}
const unauthorized = () => json({ error: 'Authentication required' }, 401);
const forbidden = () => json({ error: 'Insufficient permissions' }, 403);
async function body(request) { try { return await request.json(); } catch { return null; } }
async function assetResponse(request, env) {
  const asset = await env.ASSETS.fetch(request); const headers = new Headers(asset.headers);
  headers.set('content-security-policy', "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'");
  headers.set('referrer-policy', 'strict-origin-when-cross-origin'); headers.set('x-content-type-options', 'nosniff'); headers.set('permissions-policy', 'camera=(), microphone=(), geolocation=()');
  return new Response(asset.body, { status: asset.status, statusText: asset.statusText, headers });
}
function validEmail(email) { return typeof email === 'string' && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email); }
function appOrigin(request, env) { return env.APP_ORIGIN || new URL(request.url).origin; }
function validDate(value) { return /^\d{4}-\d{2}-\d{2}$/.test(value || '') && !Number.isNaN(Date.parse(`${value}T00:00:00Z`)); }
function validDateTime(value) { return typeof value === 'string' && /^\d{4}-\d{2}-\d{2}T.+(?:Z|[+-]\d{2}:\d{2})$/.test(value) && !Number.isNaN(Date.parse(value)); }
function cycleDueDate(endsOn, policy = 'two_calendar_days') {
  const date = new Date(`${endsOn}T00:00:00Z`);
  // The current brief says two days after each cycle. A later legacy notice
  // names the 3rd for the second cycle, so it remains an explicit deployment
  // policy rather than silently overriding the school owner's requirement.
  if (policy === 'legacy_announcement' && date.getUTCDate() !== 15) date.setUTCMonth(date.getUTCMonth() + 1, 3);
  else date.setUTCDate(date.getUTCDate() + 2);
  return date.toISOString().slice(0, 10);
}
function isValidHalfMonthCycle(startsOn, endsOn) {
  if (!validDate(startsOn) || !validDate(endsOn)) return false;
  const start = new Date(`${startsOn}T00:00:00Z`); const end = new Date(`${endsOn}T00:00:00Z`);
  if (start > end || start.getUTCFullYear() !== end.getUTCFullYear() || start.getUTCMonth() !== end.getUTCMonth()) return false;
  const lastDay = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth() + 1, 0)).getUTCDate();
  return (start.getUTCDate() === 1 && end.getUTCDate() === 15) || (start.getUTCDate() === 16 && end.getUTCDate() === lastDay);
}
async function teacherForUser(env, userId) { return env.DB.prepare('SELECT id FROM teachers WHERE user_id=?').bind(userId).first(); }
async function canAccessTeacher(env, user, teacherId) { return can(user, 'admin', 'academics', 'finance', 'lss') || (user.role === 'teacher' && (await teacherForUser(env, user.id))?.id === teacherId); }
async function canManagePayment(env, user, teacherId) { return can(user, 'admin', 'finance') || (user.role === 'teacher' && (await teacherForUser(env, user.id))?.id === teacherId); }
async function canAccessGroup(env, user, groupId) {
  if (can(user, 'admin', 'academics', 'lss')) return true;
  if (user.role !== 'teacher') return false;
  const teacher = await teacherForUser(env, user.id);
  return Boolean(teacher && await env.DB.prepare('SELECT 1 AS assigned FROM teacher_groups WHERE teacher_id=? AND group_id=?').bind(teacher.id, groupId).first());
}
async function canAccessStudent(env, user, studentId) {
  if (can(user, 'admin', 'academics', 'lss')) return true;
  if (user.role !== 'teacher') return false;
  const teacher = await teacherForUser(env, user.id);
  return Boolean(teacher && await env.DB.prepare("SELECT 1 AS assigned FROM enrollments e JOIN teacher_groups tg ON tg.group_id=e.group_id WHERE e.student_id=? AND tg.teacher_id=? AND e.status IN ('enrolled','trial') LIMIT 1").bind(studentId, teacher.id).first());
}
const maskAccount = value => value && value.length > 4 ? `••••${value.slice(-4)}` : '••••';
const onboardingBlueprint = [
  ['agreements', 'Sign contract and NDA'], ['documents', 'Verify identity and qualifications'], ['technical', 'Complete corporate account and Buzz setup'],
  ['teaching_setup', 'Configure Meet, feedback and attendance'], ['induction', 'Complete induction learning'], ['probation', 'Complete practice and probation review']
];
const adminActivityTypes = new Set(['grading', 'due_dates', 'family_communication', 'student_communication', 'approved_admin', 'approved_classwork']);
const incidentKinds = new Set(['teacher_absence', 'class_no_show', 'link_failure', 'student_placement', 'other']);
const learningModes = new Set(['group', 'one_to_one', 'club', 'unknown']);
const attendanceStatuses = new Set(['present', 'absent', 'late', 'excused']);

async function allowMagicLinkRequest(request, env, email) {
  const ip = request.headers.get('cf-connecting-ip') || request.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'unknown';
  const windowStart = new Date(Date.now() - 15 * 60 * 1000).toISOString();
  const keys = [
    { key: `email:${await hmac(email, env.AUTH_SECRET)}`, limit: 3 },
    { key: `ip:${await hmac(ip, env.AUTH_SECRET)}`, limit: 10 }
  ];
  for (const item of keys) {
    await env.DB.prepare("INSERT INTO auth_request_limits (rate_key,window_started_at,request_count,updated_at) VALUES (?,?,1,?) ON CONFLICT(rate_key) DO UPDATE SET request_count=CASE WHEN auth_request_limits.window_started_at<? THEN 1 ELSE auth_request_limits.request_count+1 END,window_started_at=CASE WHEN auth_request_limits.window_started_at<? THEN excluded.window_started_at ELSE auth_request_limits.window_started_at END,updated_at=excluded.updated_at").bind(item.key,now(),now(),windowStart,windowStart).run();
    const row = await env.DB.prepare('SELECT request_count FROM auth_request_limits WHERE rate_key=?').bind(item.key).first();
    if (!row || row.request_count > item.limit) return false;
  }
  return true;
}

async function sendMagicLink(request, env, email) {
  let user = await env.DB.prepare('SELECT * FROM users WHERE email=? AND status!="disabled"').bind(email).first();
  if (!user && env.BOOTSTRAP_ADMIN_EMAIL?.toLowerCase() === email.toLowerCase()) {
    user = { id: id(), email, name: 'School Administrator', role: 'admin', status: 'active', is_super_admin: 1 };
    await env.DB.prepare('INSERT INTO users (id,email,name,role,status,is_super_admin) VALUES (?,?,?,?,?,?)').bind(user.id, user.email, user.name, user.role, user.status, user.is_super_admin).run();
  }
  // Always return the same response to avoid exposing whether a person exists in the school directory.
  if (!user) return json({ ok: true, message: 'If this address is authorized, a sign-in link has been sent.' });
  const rawToken = b64(crypto.getRandomValues(new Uint8Array(32)));
  const expires = new Date(Date.now() + 15 * 60 * 1000).toISOString();
  await env.DB.prepare('INSERT INTO magic_links (id,user_id,token_hash,expires_at) VALUES (?,?,?,?)').bind(id(), user.id, await sha256(rawToken), expires).run();
  const link = `${appOrigin(request, env)}/auth/callback?token=${encodeURIComponent(rawToken)}`;
  if (!env.RESEND_API_KEY || !env.RESEND_FROM) return json({ error: 'Email delivery has not been configured.' }, 503);
  const delivery = await fetch('https://api.resend.com/emails', { method: 'POST', headers: { authorization: `Bearer ${env.RESEND_API_KEY}`, 'content-type': 'application/json' }, body: JSON.stringify({ from: env.RESEND_FROM, to: [user.email], subject: 'Sign in to Legacy School Workspace', html: `<p>Use this one-time link to sign in. It expires in 15 minutes.</p><p><a href="${link}">Sign in securely</a></p><p>If you did not request this, you can ignore this email.</p>` }) });
  if (!delivery.ok) return json({ error: 'Email provider rejected the request.' }, 502);
  await audit(env, user, 'auth.link_requested', 'user', user.id);
  return json({ ok: true, message: 'If this address is authorized, a sign-in link has been sent.' });
}

async function completeMagicLink(request, env) {
  const token = new URL(request.url).searchParams.get('token');
  if (!token) return new Response('Invalid sign-in link', { status: 400 });
  const row = await env.DB.prepare('SELECT m.*,u.status FROM magic_links m JOIN users u ON u.id=m.user_id WHERE m.token_hash=?').bind(await sha256(token)).first();
  if (!row || row.used_at || new Date(row.expires_at) < new Date() || !['active','invited'].includes(row.status)) return new Response('This sign-in link is invalid or has expired.', { status: 401 });
  await env.DB.prepare('UPDATE magic_links SET used_at=? WHERE id=?').bind(now(), row.id).run();
  if (row.status === 'invited') await env.DB.prepare("UPDATE users SET status='active',updated_at=? WHERE id=?").bind(now(), row.user_id).run();
  const session = await sign({ sub: row.user_id, exp: Date.now() + 8 * 60 * 60 * 1000 }, env);
  const secure = new URL(request.url).protocol === 'https:' ? '; Secure' : '';
  return new Response(null, { status: 302, headers: { location: `${appOrigin(request, env)}/`, 'set-cookie': `legacy_session=${session}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800${secure}` } });
}

async function completeGoogleOAuth(request, env) {
  const url = new URL(request.url); const state = await verify(url.searchParams.get('state'), env); const code = url.searchParams.get('code');
  if (!state || state.purpose !== 'google-oauth' || !code) return new Response('Google connection link is invalid or has expired.', { status: 401 });
  const actor = await env.DB.prepare('SELECT id,status,role FROM users WHERE id=?').bind(state.sub).first();
  if (!actor || actor.status !== 'active' || actor.role !== 'admin') return new Response('Your school account is no longer authorized to connect Google.', { status: 401 });
  if (!env.GOOGLE_CLIENT_ID || !env.GOOGLE_CLIENT_SECRET || !env.GOOGLE_REDIRECT_URI) return new Response('Google OAuth is not configured.', { status: 503 });
  const tokenResponse = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ code, client_id: env.GOOGLE_CLIENT_ID, client_secret: env.GOOGLE_CLIENT_SECRET, redirect_uri: env.GOOGLE_REDIRECT_URI, grant_type: 'authorization_code' }) });
  if (!tokenResponse.ok) return new Response('Google did not authorize the connection. Return to the workspace and try again.', { status: 502 });
  const token = await tokenResponse.json();
  if (!token.refresh_token) return new Response('Google did not return a refresh token. Reconnect and grant offline access.', { status: 502 });
  const profileResponse = await fetch('https://openidconnect.googleapis.com/v1/userinfo', { headers: { authorization: `Bearer ${token.access_token}` } });
  if (!profileResponse.ok) return new Response('Google account verification failed. Return to the workspace and try again.', { status: 502 });
  const profile = await profileResponse.json();
  const connectedAccountEmail = typeof profile.email === 'string' && profile.email_verified === true ? profile.email.trim().toLowerCase() : null;
  if (!connectedAccountEmail || !validEmail(connectedAccountEmail)) return new Response('Google did not provide a verified account email.', { status: 502 });
  const allowedAccount = env.GOOGLE_OAUTH_ALLOWED_EMAIL?.trim().toLowerCase();
  if (allowedAccount && (!validEmail(allowedAccount) || allowedAccount !== connectedAccountEmail)) return new Response('This Google account is not approved for the school connection.', { status: 403 });
  const encryptedToken = await encryptSecret(token.refresh_token, env);
  const safeConfig = JSON.stringify({ refreshToken: encryptedToken, connectedAccountEmail, scopes: token.scope?.split(' ') || [], connectedAt: now() });
  await env.DB.prepare("INSERT INTO integration_settings (provider,status,config_json,updated_at) VALUES ('google_workspace','connected',?,?) ON CONFLICT(provider) DO UPDATE SET status='connected',config_json=excluded.config_json,updated_at=excluded.updated_at").bind(safeConfig, now()).run();
  await audit(env, actor, 'integration.google.connected', 'integration', 'google_workspace');
  return Response.redirect(`${appOrigin(request, env)}/?connected=google`, 302);
}

async function googleAccessToken(env) {
  const setting = await env.DB.prepare("SELECT config_json FROM integration_settings WHERE provider='google_workspace' AND status='connected'").first();
  if (!setting) throw new Error('Google Workspace is not connected.');
  const config = JSON.parse(setting.config_json); const refreshToken = await decryptSecret(config.refreshToken, env);
  const response = await fetch('https://oauth2.googleapis.com/token', { method: 'POST', headers: { 'content-type': 'application/x-www-form-urlencoded' }, body: new URLSearchParams({ client_id: env.GOOGLE_CLIENT_ID, client_secret: env.GOOGLE_CLIENT_SECRET, refresh_token: refreshToken, grant_type: 'refresh_token' }) });
  if (!response.ok) throw new Error('Google access-token refresh failed. Reconnect Google Workspace.');
  const token = await response.json(); return { accessToken: token.access_token, config };
}

async function dashboard(env, user) {
  if (user.role === 'teacher') {
    const teacher = await teacherForUser(env, user.id);
    if (!teacher) return { activeTeachers: 0, onboardingOpen: 0, classesToday: 0, adminHours: 0, portal: 'teacher' };
    const [onboarding, events, adminHours] = await env.DB.batch([
      env.DB.prepare("SELECT count(*) AS count FROM onboarding_items WHERE teacher_id=? AND status IN ('not_started','in_progress','blocked')").bind(teacher.id),
      env.DB.prepare("SELECT count(*) AS count FROM calendar_events e JOIN teacher_groups tg ON tg.group_id=e.group_id WHERE tg.teacher_id=? AND date(e.starts_at)=date('now')").bind(teacher.id),
      env.DB.prepare("SELECT coalesce(sum(hours),0) AS hours FROM time_entries WHERE teacher_id=? AND strftime('%Y-%m', worked_on)=strftime('%Y-%m','now')").bind(teacher.id)
    ]);
    return { activeTeachers: 1, onboardingOpen: onboarding.results[0].count, classesToday: events.results[0].count, adminHours: adminHours.results[0].hours, portal: 'teacher' };
  }
  const [teachers, onboarding, events, adminHours] = await env.DB.batch([
    env.DB.prepare("SELECT count(*) AS count FROM teachers WHERE status='active'"),
    env.DB.prepare("SELECT count(*) AS count FROM onboarding_items WHERE status IN ('not_started','in_progress','blocked')"),
    env.DB.prepare("SELECT count(*) AS count FROM calendar_events WHERE date(starts_at)=date('now')"),
    env.DB.prepare("SELECT coalesce(sum(hours),0) AS hours FROM time_entries WHERE strftime('%Y-%m', worked_on)=strftime('%Y-%m','now')")
  ]);
  return { activeTeachers: teachers.results[0].count, onboardingOpen: onboarding.results[0].count, classesToday: events.results[0].count, adminHours: adminHours.results[0].hours, portal: 'operations' };
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (url.pathname === '/auth/callback' && request.method === 'GET') return completeMagicLink(request, env);
    if (url.pathname === '/auth/google/callback' && request.method === 'GET') return completeGoogleOAuth(request, env);
    if (!url.pathname.startsWith('/api/')) return assetResponse(request, env);
    if (url.pathname === '/api/health') return json({ ok: true, service: 'legacy-school-workspace' });
    if (url.pathname === '/api/auth/request-link' && request.method === 'POST') { const data = await body(request); if(!validEmail(data?.email))return json({ error: 'A valid email is required.' }, 400); const email=data.email.trim().toLowerCase(); if(!await allowMagicLinkRequest(request,env,email))return json({ok:true,message:'If this address is authorized, a sign-in link has been sent.'}); return sendMagicLink(request, env, email); }
    if (url.pathname === '/api/auth/logout' && request.method === 'POST') { const secure = new URL(request.url).protocol === 'https:' ? '; Secure' : ''; return json({ok:true},200,{'set-cookie':`legacy_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0${secure}`}); }
    if (url.pathname === '/api/security/report-recipients' && request.method === 'POST') { const token=(request.headers.get('authorization')||'').replace(/^Bearer\s+/i,''); if(!await secretMatches(token,env.SECURITY_REPORT_TOKEN))return json({error:'Unauthorized'},401); const recipients=await env.DB.prepare("SELECT DISTINCT u.email FROM users u LEFT JOIN security_report_recipients r ON r.user_id=u.id LEFT JOIN security_report_settings s ON s.owner_user_id=u.id WHERE u.status='active' AND ((r.active=1) OR s.id=1) ORDER BY u.email LIMIT 20").all(); return json({recipients:recipients.results.map(row=>row.email)},200,{'cache-control':'no-store'}); }
    const user = await currentUser(request, env); if (!user) return unauthorized();
    if (url.pathname === '/api/me') return json({ user });
    if (url.pathname === '/api/security/report-settings' && request.method === 'GET') { if(!isSecurityOwner(user))return forbidden(); const [settings,personnel]=await env.DB.batch([env.DB.prepare('SELECT owner_user_id,updated_at FROM security_report_settings WHERE id=1'),env.DB.prepare("SELECT u.id,u.name,u.email,u.role,u.status,coalesce(r.active,0) AS selected FROM users u LEFT JOIN security_report_recipients r ON r.user_id=u.id WHERE u.status='active' AND u.role IN ('admin','academics','lss','finance') ORDER BY u.name")]); return json({ownerUserId:settings.results[0]?.owner_user_id||null,updatedAt:settings.results[0]?.updated_at||null,personnel:personnel.results}); }
    if (url.pathname === '/api/security/report-settings' && request.method === 'PUT') { if(!isSecurityOwner(user))return forbidden(); const d=await body(request); if(typeof d?.ownerUserId!=='string'||!Array.isArray(d.recipientUserIds)||d.recipientUserIds.length>20||d.recipientUserIds.some(value=>typeof value!=='string'))return json({error:'ownerUserId and up to 20 recipientUserIds are required.'},400); const ids=[...new Set([d.ownerUserId,...d.recipientUserIds])]; const placeholders=ids.map(()=>'?').join(','); const people=await env.DB.prepare(`SELECT id,role,status,is_super_admin FROM users WHERE id IN (${placeholders})`).bind(...ids).all(); if(people.results.length!==ids.length||people.results.some(person=>person.status!=='active'))return json({error:'All selected personnel must be active school users.'},400); const owner=people.results.find(person=>person.id===d.ownerUserId); if(!owner||owner.role!=='admin'||Number(owner.is_super_admin)!==1)return json({error:'The report owner must be an active Super Admin.'},400); const statements=[env.DB.prepare('DELETE FROM security_report_recipients').bind(),env.DB.prepare('INSERT INTO security_report_settings (id,owner_user_id,updated_by_user_id,updated_at) VALUES (1,?,?,?) ON CONFLICT(id) DO UPDATE SET owner_user_id=excluded.owner_user_id,updated_by_user_id=excluded.updated_by_user_id,updated_at=excluded.updated_at').bind(d.ownerUserId,user.id,now())]; for(const recipientId of d.recipientUserIds)statements.push(env.DB.prepare('INSERT INTO security_report_recipients (user_id,active,updated_by_user_id,updated_at) VALUES (?,1,?,?)').bind(recipientId,user.id,now())); await env.DB.batch(statements); await audit(env,user,'security_report.settings_updated','security_report_settings','1',{recipientCount:d.recipientUserIds.length,ownerUserId:d.ownerUserId}); return json({ok:true}); }
    if (url.pathname === '/api/staff' && request.method === 'GET') { if(!isSecurityOwner(user))return forbidden(); const staff=await env.DB.prepare("SELECT id,name,email,role,status,is_super_admin,created_at,updated_at FROM users WHERE role IN ('admin','academics','finance','lss') ORDER BY CASE WHEN is_super_admin=1 THEN 0 ELSE 1 END,name").all(); return json({staff:staff.results}); }
    if (url.pathname === '/api/staff' && request.method === 'POST') { if(!isSecurityOwner(user))return forbidden(); const d=await body(request); const roles=new Set(['admin','academics','finance','lss']); if(typeof d?.name!=='string'||!d.name.trim()||d.name.trim().length>200||!validEmail(d.email)||!roles.has(d.role))return json({error:'name, a valid email, and an operational role are required.'},400); const email=d.email.trim().toLowerCase(); const existing=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first(); if(existing)return json({error:'A school account already exists for this email.'},409); const staff={id:id(),name:d.name.trim(),email,role:d.role,status:'invited'}; await env.DB.prepare('INSERT INTO users (id,email,name,role,status) VALUES (?,?,?,?,?)').bind(staff.id,staff.email,staff.name,staff.role,staff.status).run(); await audit(env,user,'staff.created','user',staff.id,{role:staff.role}); return json({staff},201); }
    const staffInvite=url.pathname.match(/^\/api\/staff\/([^/]+)\/invite$/);
    if (staffInvite && request.method === 'POST') { if(!isSecurityOwner(user))return forbidden(); if(!env.RESEND_API_KEY||!env.RESEND_FROM)return json({error:'Email delivery has not been configured.'},503); const staff=await env.DB.prepare("SELECT id,name,email,role,status FROM users WHERE id=? AND role IN ('admin','academics','finance','lss') AND status!='disabled'").bind(staffInvite[1]).first(); if(!staff)return json({error:'An active operational staff account was not found.'},404); const recent=await env.DB.prepare("SELECT id FROM operational_staff_invitation_sends WHERE staff_user_id=? AND julianday(sent_at)>julianday('now','-1 day') ORDER BY sent_at DESC LIMIT 1").bind(staff.id).first(); if(recent)return json({error:'An operational staff invitation was already sent in the last 24 hours.'},409); const rawToken=b64(crypto.getRandomValues(new Uint8Array(32))); const expires=new Date(Date.now()+15*60*1000).toISOString(); await env.DB.prepare('INSERT INTO magic_links (id,user_id,token_hash,expires_at) VALUES (?,?,?,?)').bind(id(),staff.id,await sha256(rawToken),expires).run(); const link=`${appOrigin(request,env)}/auth/callback?token=${encodeURIComponent(rawToken)}`; const delivery=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:env.RESEND_FROM,to:[staff.email],subject:'Invitation to Legacy School Workspace',text:`Hello ${staff.name},\n\nYou have been invited to Legacy School Workspace as ${staff.role.replaceAll('_',' ')}. Use this one-time link to activate your account. It expires in 15 minutes:\n${link}\n\nLegacy School Operations`})}); if(!delivery.ok)return json({error:'Email provider rejected the invitation.'},502); await env.DB.prepare('INSERT INTO operational_staff_invitation_sends (id,staff_user_id,sent_by_user_id,sent_at) VALUES (?,?,?,?)').bind(id(),staff.id,user.id,now()).run(); await audit(env,user,'staff.invited','user',staff.id,{role:staff.role}); return json({ok:true}); }
    if (url.pathname === '/api/dashboard' && request.method === 'GET') return json(await dashboard(env,user));
    if (url.pathname === '/api/teachers' && request.method === 'GET') { const own= user.role==='teacher' ? await teacherForUser(env,user.id) : null; const rows = await env.DB.prepare(`SELECT t.id,t.full_name,t.email,t.role_title,t.status,t.school_account_status,t.payment_platform,t.created_at,coalesce(group_concat(g.name, ', '),'—') AS groups FROM teachers t LEFT JOIN teacher_groups tg ON tg.teacher_id=t.id LEFT JOIN groups g ON g.id=tg.group_id ${own?'WHERE t.id=?':''} GROUP BY t.id ORDER BY t.full_name`).bind(...(own?[own.id]:[])).all(); return json({ teachers: rows.results }); }
    if (url.pathname === '/api/teachers' && request.method === 'POST') { if (!can(user,'admin','academics','lss')) return forbidden(); const d=await body(request); if(!d?.fullName || !validEmail(d.email) || !d.roleTitle) return json({error:'fullName, email and roleTitle are required.'},400); const email=d.email.trim().toLowerCase(); const existingTeacher=await env.DB.prepare('SELECT id FROM teachers WHERE email=?').bind(email).first(); if(existingTeacher)return json({error:'A teacher record already exists for this email.'},409); const existingUser=await env.DB.prepare('SELECT id,role,status FROM users WHERE email=?').bind(email).first(); if(existingUser&&existingUser.role!=='teacher')return json({error:'This email already belongs to a non-teacher school account.'},409); const account=existingUser||{id:id(),role:'teacher',status:'invited'}; const teacher={id:id(),userId:account.id,fullName:d.fullName.trim(),email,roleTitle:d.roleTitle.trim(),status:'candidate'}; const statements=[env.DB.prepare('INSERT INTO teachers (id,user_id,full_name,email,role_title,status) VALUES (?,?,?,?,?,?)').bind(teacher.id,teacher.userId,teacher.fullName,teacher.email,teacher.roleTitle,teacher.status)]; if(!existingUser)statements.unshift(env.DB.prepare('INSERT INTO users (id,email,name,role,status) VALUES (?,?,?,?,?)').bind(account.id,email,teacher.fullName,'teacher','invited')); await env.DB.batch(statements); await audit(env,user,'teacher.created','teacher',teacher.id,{userId:teacher.userId,accountStatus:account.status}); return json({teacher:{...teacher,accountStatus:account.status}},201); }
    const paymentDetails = url.pathname.match(/^\/api\/teachers\/([^/]+)\/payment-details$/);
    if (paymentDetails && request.method === 'PUT') { const teacherId=paymentDetails[1]; if(!await canManagePayment(env,user,teacherId))return forbidden(); const d=await body(request); if(typeof d?.paymentPlatform!=='string'||typeof d?.accountName!=='string'||typeof d?.accountNumber!=='string'||!d.paymentPlatform.trim()||!d.accountName.trim()||!d.accountNumber.trim()||d.accountNumber.length>200)return json({error:'paymentPlatform, accountName and accountNumber are required.'},400); if(!await env.DB.prepare('SELECT id FROM teachers WHERE id=?').bind(teacherId).first())return json({error:'Teacher not found.'},404); const encrypted=JSON.stringify(await encryptSecret(d.accountNumber.trim(),env)); await env.DB.prepare('UPDATE teachers SET payment_platform=?,payment_account_name=?,payment_account_number_encrypted=?,updated_at=? WHERE id=?').bind(d.paymentPlatform.trim(),d.accountName.trim(),encrypted,now(),teacherId).run(); await audit(env,user,'payment_details.updated','teacher',teacherId); return json({ok:true,accountNumberMasked:maskAccount(d.accountNumber.trim())}); }
    if (paymentDetails && request.method === 'GET') { const teacherId=paymentDetails[1]; if(!await canManagePayment(env,user,teacherId))return forbidden(); const payment=await env.DB.prepare('SELECT payment_platform,payment_account_name,payment_account_number_encrypted FROM teachers WHERE id=?').bind(teacherId).first(); if(!payment)return json({error:'Teacher not found.'},404); const result={paymentPlatform:payment.payment_platform,accountName:payment.payment_account_name,accountNumberMasked:payment.payment_account_number_encrypted?'••••':null}; if(url.searchParams.get('reveal')==='1'){if(!can(user,'admin','finance'))return forbidden(); result.accountNumber=await decryptSecret(JSON.parse(payment.payment_account_number_encrypted),env); result.accountNumberMasked=maskAccount(result.accountNumber); await audit(env,user,'payment_details.revealed','teacher',teacherId);} return json(result,200,{'cache-control':'no-store'}); }
    const teacherInvite = url.pathname.match(/^\/api\/teachers\/([^/]+)\/invite$/);
    if (teacherInvite && request.method === 'POST') {
      if(!can(user,'admin','academics','lss'))return forbidden();
      if(!env.RESEND_API_KEY||!env.RESEND_FROM)return json({error:'Email delivery has not been configured.'},503);
      const teacher=await env.DB.prepare("SELECT t.id,t.full_name,t.email,u.id AS user_id,u.status AS account_status FROM teachers t JOIN users u ON u.id=t.user_id WHERE t.id=? AND u.status!='disabled'").bind(teacherInvite[1]).first();
      if(!teacher)return json({error:'An active teacher account was not found.'},404);
      const recent=await env.DB.prepare("SELECT id FROM teacher_invitation_sends WHERE teacher_id=? AND julianday(sent_at)>julianday('now','-1 day') ORDER BY sent_at DESC LIMIT 1").bind(teacher.id).first();
      if(recent)return json({error:'An onboarding invitation was already sent for this teacher in the last 24 hours.'},409);
      const onboarding=await env.DB.prepare('SELECT title,due_at FROM onboarding_items WHERE teacher_id=? ORDER BY created_at').bind(teacher.id).all();
      const rawToken=b64(crypto.getRandomValues(new Uint8Array(32)));
      const expires=new Date(Date.now()+15*60*1000).toISOString();
      await env.DB.prepare('INSERT INTO magic_links (id,user_id,token_hash,expires_at) VALUES (?,?,?,?)').bind(id(),teacher.user_id,await sha256(rawToken),expires).run();
      const tasks=onboarding.results.length?onboarding.results.map(item=>`- ${item.title}${item.due_at?` (due ${item.due_at})`:''}`).join('\n'):'- Your onboarding tasks will be added by school operations.';
      const link=`${appOrigin(request,env)}/auth/callback?token=${encodeURIComponent(rawToken)}`;
      const delivery=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:env.RESEND_FROM,to:[teacher.email],subject:'Welcome to Legacy School Workspace',text:`Hello ${teacher.full_name},\n\nWelcome to Legacy School. Use this one-time link to activate your workspace and begin your onboarding tasks. It expires in 15 minutes:\n${link}\n\nYour current onboarding checklist:\n${tasks}\n\nPlease keep your evidence and progress up to date in the workspace.\n\nLegacy School Operations`})});
      if(!delivery.ok)return json({error:'Email provider rejected the invitation.'},502);
      await env.DB.prepare('INSERT INTO teacher_invitation_sends (id,teacher_id,sent_by_user_id,sent_at) VALUES (?,?,?,?)').bind(id(),teacher.id,user.id,now()).run();
      await audit(env,user,'teacher.onboarding_invited','teacher',teacher.id,{onboardingItems:onboarding.results.length});
      return json({ok:true});
    }
    const onboardingTeacher = url.pathname.match(/^\/api\/teachers\/([^/]+)\/onboarding$/);
    if (onboardingTeacher && request.method === 'GET') { const teacherId=onboardingTeacher[1]; if(!await canAccessTeacher(env,user,teacherId)) return forbidden(); const items=await env.DB.prepare('SELECT id,kind,title,status,due_at,evidence_url,owner_user_id,completed_at FROM onboarding_items WHERE teacher_id=? ORDER BY created_at').bind(teacherId).all(); return json({items:items.results}); }
    if (onboardingTeacher && request.method === 'POST') { if(!can(user,'admin','academics','lss')) return forbidden(); const teacherId=onboardingTeacher[1]; const teacher=await env.DB.prepare('SELECT id FROM teachers WHERE id=?').bind(teacherId).first(); if(!teacher)return json({error:'Teacher not found.'},404); const existing=await env.DB.prepare('SELECT count(*) AS count FROM onboarding_items WHERE teacher_id=?').bind(teacherId).first(); if(existing.count) return json({error:'This teacher already has an onboarding pathway.'},409); const dueAt=(await body(request))?.dueAt||null; const statements=onboardingBlueprint.map(([kind,title])=>env.DB.prepare('INSERT INTO onboarding_items (id,teacher_id,kind,title,due_at,owner_user_id) VALUES (?,?,?,?,?,?)').bind(id(),teacherId,kind,title,dueAt,user.id)); await env.DB.batch(statements); await env.DB.prepare("UPDATE teachers SET status='onboarding',updated_at=? WHERE id=?").bind(now(),teacherId).run(); await audit(env,user,'onboarding.seeded','teacher',teacherId); return json({ok:true, created:onboardingBlueprint.length},201); }
    const onboardingItem = url.pathname.match(/^\/api\/onboarding\/([^/]+)$/);
    if (onboardingItem && request.method === 'PATCH') { const item=await env.DB.prepare('SELECT id,teacher_id FROM onboarding_items WHERE id=?').bind(onboardingItem[1]).first(); if(!item)return json({error:'Onboarding item not found.'},404); if(!await canAccessTeacher(env,user,item.teacher_id))return forbidden(); const d=await body(request); if(!['not_started','in_progress','complete','blocked'].includes(d?.status)) return json({error:'A valid status is required.'},400); const evidence=typeof d.evidenceUrl==='string'?d.evidenceUrl:null; const completed=d.status==='complete'?now():null; await env.DB.prepare('UPDATE onboarding_items SET status=?,evidence_url=coalesce(?,evidence_url),completed_at=? WHERE id=?').bind(d.status,evidence,completed,item.id).run(); await audit(env,user,'onboarding.updated','onboarding_item',item.id,{status:d.status}); return json({ok:true}); }
    const onboardingReminder = url.pathname.match(/^\/api\/onboarding\/([^/]+)\/remind$/);
    if (onboardingReminder && request.method === 'POST') { if(!can(user,'admin','academics','lss'))return forbidden(); if(!env.RESEND_API_KEY||!env.RESEND_FROM)return json({error:'Email delivery has not been configured.'},503); const item=await env.DB.prepare('SELECT oi.id,oi.title,oi.due_at,t.full_name,t.email FROM onboarding_items oi JOIN teachers t ON t.id=oi.teacher_id WHERE oi.id=?').bind(onboardingReminder[1]).first(); if(!item)return json({error:'Onboarding item not found.'},404); const recent=await env.DB.prepare("SELECT id FROM onboarding_reminders WHERE onboarding_item_id=? AND julianday(sent_at)>julianday('now','-1 day') ORDER BY sent_at DESC LIMIT 1").bind(item.id).first(); if(recent)return json({error:'A reminder was already sent for this item in the last 24 hours.'},409); const due=item.due_at?` Due: ${item.due_at}.`:''; const delivery=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:env.RESEND_FROM,to:[item.email],subject:`Reminder: ${item.title}`,text:`Hello ${item.full_name},\n\nThis is a reminder to complete your onboarding task: ${item.title}.${due}\n\nOpen the Legacy School Workspace to update the item or add evidence.\n\nLegacy School Operations`})}); if(!delivery.ok)return json({error:'Email provider rejected the reminder.'},502); await env.DB.prepare('INSERT INTO onboarding_reminders (id,onboarding_item_id,sent_by_user_id,recipient_email,sent_at) VALUES (?,?,?,?,?)').bind(id(),item.id,user.id,item.email,now()).run(); await audit(env,user,'onboarding.reminder_sent','onboarding_item',item.id,{recipient:item.email}); return json({ok:true}); }
    if (url.pathname === '/api/groups' && request.method === 'GET') { const own=user.role==='teacher'?await teacherForUser(env,user.id):null; const groups=await env.DB.prepare(`SELECT g.id,g.name,g.grade_band,g.course_name,g.calendar_id,g.meet_url FROM groups g ${own?'JOIN teacher_groups tg ON tg.group_id=g.id WHERE tg.teacher_id=?':''} ORDER BY g.grade_band,g.course_name,g.name`).bind(...(own?[own.id]:[])).all(); return json({groups:groups.results}); }
    if (url.pathname === '/api/groups' && request.method === 'POST') { if(!can(user,'admin','academics','lss'))return forbidden(); const d=await body(request); if(!d?.name||!d?.gradeBand||!d?.courseName)return json({error:'name, gradeBand and courseName are required.'},400); const group={id:id(),name:d.name.trim(),gradeBand:d.gradeBand.trim(),courseName:d.courseName.trim(),calendarId:d.calendarId||null,meetUrl:d.meetUrl||null}; await env.DB.prepare('INSERT INTO groups (id,name,grade_band,course_name,calendar_id,meet_url) VALUES (?,?,?,?,?,?)').bind(group.id,group.name,group.gradeBand,group.courseName,group.calendarId,group.meetUrl).run(); await audit(env,user,'group.created','group',group.id); return json({group},201); }
    const teacherGroup = url.pathname.match(/^\/api\/teachers\/([^/]+)\/groups\/([^/]+)$/);
    if (teacherGroup && request.method === 'PUT') { if(!can(user,'admin','academics','lss'))return forbidden(); const [teacherId,groupId]=teacherGroup.slice(1); await env.DB.prepare('INSERT OR IGNORE INTO teacher_groups (teacher_id,group_id) VALUES (?,?)').bind(teacherId,groupId).run(); await audit(env,user,'teacher.group_assigned','teacher',teacherId,{groupId}); return json({ok:true}); }
    if (url.pathname === '/api/students' && request.method === 'GET') { if(!can(user,'admin','academics','lss','teacher'))return forbidden(); const own=user.role==='teacher'; const students=await env.DB.prepare(`SELECT s.id,s.full_name,s.preferred_name,s.school_email,s.grade_level,s.status,s.created_at,coalesce(group_concat(DISTINCT g.name),'—') AS groups FROM students s ${own?"JOIN enrollments e ON e.student_id=s.id JOIN teacher_groups tg ON tg.group_id=e.group_id JOIN groups g ON g.id=e.group_id WHERE tg.teacher_id=? AND e.status IN ('enrolled','trial')":"LEFT JOIN enrollments e ON e.student_id=s.id AND e.status IN ('enrolled','trial') LEFT JOIN groups g ON g.id=e.group_id"} GROUP BY s.id ORDER BY s.full_name LIMIT 500`).bind(...(own?[ (await teacherForUser(env,user.id))?.id||'__none__' ]:[])).all(); return json({students:students.results}); }
    if (url.pathname === '/api/students' && request.method === 'POST') { if(!can(user,'admin','academics','lss'))return forbidden(); const d=await body(request); if(typeof d?.fullName!=='string'||!d.fullName.trim()||typeof d?.gradeLevel!=='string'||!d.gradeLevel.trim()||(d.schoolEmail&&!validEmail(d.schoolEmail)))return json({error:'fullName, gradeLevel and an optional valid schoolEmail are required.'},400); if(d.guardianContact!==undefined&&(typeof d.guardianContact!=='object'||d.guardianContact===null))return json({error:'guardianContact must be an object when supplied.'},400); const guardian=d.guardianContact?JSON.stringify(await encryptSecret(JSON.stringify(d.guardianContact),env)):null; const student={id:id(),fullName:d.fullName.trim(),preferredName:typeof d.preferredName==='string'?d.preferredName.trim()||null:null,schoolEmail:d.schoolEmail?.trim().toLowerCase()||null,gradeLevel:d.gradeLevel.trim(),status:['active','inactive','withdrawn'].includes(d.status)?d.status:'active'}; await env.DB.prepare('INSERT INTO students (id,full_name,preferred_name,school_email,grade_level,status,guardian_contact_encrypted) VALUES (?,?,?,?,?,?,?)').bind(student.id,student.fullName,student.preferredName,student.schoolEmail,student.gradeLevel,student.status,guardian).run(); await audit(env,user,'student.created','student',student.id,{guardianContactStored:Boolean(guardian)}); return json({student},201); }
    const studentRoute=url.pathname.match(/^\/api\/students\/([^/]+)$/);
    if (studentRoute && request.method === 'GET') { if(!await canAccessStudent(env,user,studentRoute[1]))return forbidden(); const student=await env.DB.prepare('SELECT id,full_name,preferred_name,school_email,grade_level,status,created_at,updated_at FROM students WHERE id=?').bind(studentRoute[1]).first(); return student?json({student}):json({error:'Student not found.'},404); }
    const guardianRoute=url.pathname.match(/^\/api\/students\/([^/]+)\/guardian$/);
    if (guardianRoute && request.method === 'GET') { if(!can(user,'admin','academics','lss'))return forbidden(); const student=await env.DB.prepare('SELECT id,guardian_contact_encrypted FROM students WHERE id=?').bind(guardianRoute[1]).first(); if(!student)return json({error:'Student not found.'},404); const guardianContact=student.guardian_contact_encrypted?JSON.parse(await decryptSecret(JSON.parse(student.guardian_contact_encrypted),env)):null; await audit(env,user,'student.guardian_revealed','student',student.id); return json({guardianContact},200,{'cache-control':'no-store'}); }
    if (guardianRoute && request.method === 'PUT') { if(!can(user,'admin','academics','lss'))return forbidden(); const d=await body(request); if(typeof d?.guardianContact!=='object'||d.guardianContact===null)return json({error:'guardianContact is required.'},400); const student=await env.DB.prepare('SELECT id FROM students WHERE id=?').bind(guardianRoute[1]).first(); if(!student)return json({error:'Student not found.'},404); const encrypted=JSON.stringify(await encryptSecret(JSON.stringify(d.guardianContact),env)); await env.DB.prepare('UPDATE students SET guardian_contact_encrypted=?,updated_at=? WHERE id=?').bind(encrypted,now(),student.id).run(); await audit(env,user,'student.guardian_updated','student',student.id); return json({ok:true}); }
    const enrollmentRoute=url.pathname.match(/^\/api\/students\/([^/]+)\/enrollments\/([^/]+)$/);
    if (enrollmentRoute && request.method === 'PUT') { if(!can(user,'admin','academics','lss'))return forbidden(); const d=await body(request); const [studentId,groupId]=enrollmentRoute.slice(1); const status=['enrolled','trial','withdrawn'].includes(d?.status)?d.status:'enrolled'; const enrolledOn=d?.enrolledOn||now().slice(0,10); if(!validDate(enrolledOn)||(d?.endedOn&&!validDate(d.endedOn))||(d?.endedOn&&d.endedOn<enrolledOn))return json({error:'Valid enrolledOn and optional endedOn dates are required.'},400); const [student,group]=await env.DB.batch([env.DB.prepare('SELECT id FROM students WHERE id=?').bind(studentId),env.DB.prepare('SELECT id FROM groups WHERE id=?').bind(groupId)]); if(!student.results[0]||!group.results[0])return json({error:'Student or group not found.'},404); const enrollment={id:id(),studentId,groupId,status,enrolledOn,endedOn:d?.endedOn||null}; await env.DB.prepare('INSERT INTO enrollments (id,student_id,group_id,status,enrolled_on,ended_on) VALUES (?,?,?,?,?,?)').bind(enrollment.id,enrollment.studentId,enrollment.groupId,enrollment.status,enrollment.enrolledOn,enrollment.endedOn).run(); await audit(env,user,'student.enrolled','enrollment',enrollment.id,{studentId,groupId,status}); return json({enrollment},201); }
    const rosterRoute=url.pathname.match(/^\/api\/groups\/([^/]+)\/roster$/);
    if (rosterRoute && request.method === 'GET') { const groupId=rosterRoute[1]; if(!await canAccessGroup(env,user,groupId))return forbidden(); const scheduledFor=url.searchParams.get('scheduledFor')||now().slice(0,10); if(!validDate(scheduledFor))return json({error:'scheduledFor must be an ISO date.'},400); const roster=await env.DB.prepare("SELECT e.id AS enrollment_id,e.status AS enrollment_status,s.id AS student_id,s.full_name,s.preferred_name,s.grade_level,a.status AS attendance_status FROM enrollments e JOIN students s ON s.id=e.student_id LEFT JOIN attendance_records a ON a.enrollment_id=e.id AND a.scheduled_for=? WHERE e.group_id=? AND e.status IN ('enrolled','trial') AND e.enrolled_on<=? AND (e.ended_on IS NULL OR e.ended_on>=?) ORDER BY s.full_name").bind(scheduledFor,groupId,scheduledFor,scheduledFor).all(); return json({scheduledFor,roster:roster.results.map(row=>({...row,attendance_status:row.attendance_status||'unmarked'}))}); }
    if (url.pathname === '/api/attendance' && request.method === 'POST') { if(!can(user,'admin','academics','lss','teacher'))return forbidden(); const d=await body(request); if(!d?.groupId||!validDate(d.scheduledFor)||!Array.isArray(d.records)||!d.records.length||d.records.length>200||d.records.some(record=>!record?.enrollmentId||!attendanceStatuses.has(record.status)))return json({error:'groupId, scheduledFor and 1–200 attendance records with valid statuses are required.'},400); if(!await canAccessGroup(env,user,d.groupId))return forbidden(); const enrollmentIds=[...new Set(d.records.map(record=>record.enrollmentId))]; if(enrollmentIds.length!==d.records.length)return json({error:'Each enrollment may be marked once per submission.'},400); const placeholders=enrollmentIds.map(()=>'?').join(','); const enrolled=await env.DB.prepare(`SELECT id FROM enrollments WHERE group_id=? AND status IN ('enrolled','trial') AND id IN (${placeholders})`).bind(d.groupId,...enrollmentIds).all(); if(enrolled.results.length!==enrollmentIds.length)return json({error:'Attendance can only be recorded for enrolled or trial students in this group.'},409); const statements=d.records.map(record=>env.DB.prepare("INSERT INTO attendance_records (id,enrollment_id,scheduled_for,status,marked_by_user_id) VALUES (?,?,?,?,?) ON CONFLICT(enrollment_id,scheduled_for) DO UPDATE SET status=excluded.status,marked_by_user_id=excluded.marked_by_user_id,updated_at=CURRENT_TIMESTAMP").bind(id(),record.enrollmentId,d.scheduledFor,record.status,user.id)); await env.DB.batch(statements); await audit(env,user,'attendance.recorded','group',d.groupId,{scheduledFor:d.scheduledFor,records:d.records.length}); return json({ok:true,records:d.records.length}); }
    if (url.pathname === '/api/time-entries' && request.method === 'GET') { let teacherId=url.searchParams.get('teacherId'); if(user.role==='teacher') teacherId=(await teacherForUser(env,user.id))?.id||'__none__'; if(teacherId&&!await canAccessTeacher(env,user,teacherId))return forbidden(); const entries=await env.DB.prepare(`SELECT te.id,te.teacher_id,t.full_name AS teacher_name,te.activity_type,te.hours,te.worked_on,te.evidence_url,te.approval_status,te.created_at FROM time_entries te JOIN teachers t ON t.id=te.teacher_id ${teacherId?'WHERE te.teacher_id=?':''} ORDER BY te.worked_on DESC LIMIT 200`).bind(...(teacherId?[teacherId]:[])).all(); return json({entries:entries.results}); }
    if (url.pathname === '/api/time-entries' && request.method === 'POST') { if (!can(user,'admin','academics','lss','teacher')) return forbidden(); const d=await body(request); if(!d?.teacherId || !adminActivityTypes.has(d.activityType) || !Number.isFinite(+d.hours) || +d.hours<=0 || +d.hours>8 || !validDate(d.workedOn)) return json({error:'teacherId, a supported non-live activity, 0–8 hours and workedOn are required.'},400); if(!await canAccessTeacher(env,user,d.teacherId))return forbidden(); const total=await env.DB.prepare("SELECT coalesce(sum(hours),0) AS hours FROM time_entries WHERE teacher_id=? AND strftime('%Y-%m',worked_on)=strftime('%Y-%m',?) AND approval_status!='rejected'").bind(d.teacherId,d.workedOn).first(); if(+total.hours + +d.hours > 8) return json({error:'Monthly 8-hour non-class cap exceeded. Submit for an exception instead.'},409); const entry={id:id(),teacherId:d.teacherId,activityType:d.activityType,hours:+d.hours,workedOn:d.workedOn,evidenceUrl:d.evidenceUrl||null}; await env.DB.prepare('INSERT INTO time_entries (id,teacher_id,activity_type,hours,worked_on,evidence_url) VALUES (?,?,?,?,?,?)').bind(entry.id,entry.teacherId,entry.activityType,entry.hours,entry.workedOn,entry.evidenceUrl).run(); await audit(env,user,'time_entry.created','time_entry',entry.id); return json({entry},201); }
    const timeEntry = url.pathname.match(/^\/api\/time-entries\/([^/]+)$/);
    if (timeEntry && request.method === 'PATCH') { if(!can(user,'admin','finance','academics','lss'))return forbidden(); const d=await body(request); if(!['approved','rejected'].includes(d?.approvalStatus))return json({error:'approvalStatus must be approved or rejected.'},400); const entry=await env.DB.prepare('SELECT id FROM time_entries WHERE id=?').bind(timeEntry[1]).first(); if(!entry)return json({error:'Time entry not found.'},404); await env.DB.prepare('UPDATE time_entries SET approval_status=? WHERE id=?').bind(d.approvalStatus,entry.id).run(); await audit(env,user,'time_entry.approval_updated','time_entry',entry.id,{approvalStatus:d.approvalStatus}); return json({ok:true}); }
    const salarySubmissions=url.pathname.match(/^\/api\/pay-cycles\/([^/]+)\/salary-reports$/);
    if (salarySubmissions && request.method === 'GET') {
      const cycleId=salarySubmissions[1];
      const cycle=await env.DB.prepare('SELECT id FROM pay_cycles WHERE id=?').bind(cycleId).first();
      if(!cycle)return json({error:'Payment cycle not found.'},404);
      if(user.role==='teacher'){
        const teacher=await teacherForUser(env,user.id); if(!teacher)return json({reports:[]});
        const reports=await env.DB.prepare('SELECT id,cycle_id,teacher_id,group_attended_count,group_no_show_count,one_to_one_attended_count,one_to_one_no_show_count,one_to_one_trial_count,notes,evidence_url,submitted_late,status,submitted_at,reviewed_at,review_note,updated_at FROM salary_report_submissions WHERE cycle_id=? AND teacher_id=?').bind(cycleId,teacher.id).all();
        return json({reports:reports.results});
      }
      if(!can(user,'admin','finance','academics'))return forbidden();
      const reports=await env.DB.prepare('SELECT s.id,s.cycle_id,s.teacher_id,t.full_name AS teacher_name,t.email AS teacher_email,t.payment_platform,t.payment_account_name,s.group_attended_count,s.group_no_show_count,s.one_to_one_attended_count,s.one_to_one_no_show_count,s.one_to_one_trial_count,s.notes,s.evidence_url,s.submitted_late,s.status,s.submitted_at,s.reviewed_at,s.review_note,s.updated_at FROM salary_report_submissions s JOIN teachers t ON t.id=s.teacher_id WHERE s.cycle_id=? ORDER BY t.full_name').bind(cycleId).all();
      return json({reports:reports.results});
    }
    if (salarySubmissions && request.method === 'POST') {
      if(user.role!=='teacher')return forbidden();
      const teacher=await teacherForUser(env,user.id); if(!teacher)return json({error:'This account has no linked teacher record.'},409);
      const cycle=await env.DB.prepare('SELECT id,submission_due_on,status FROM pay_cycles WHERE id=?').bind(salarySubmissions[1]).first();
      if(!cycle)return json({error:'Payment cycle not found.'},404);
      if(cycle.status!=='open')return json({error:'Salary reports can only be submitted while a payment cycle is open.'},409);
      const d=await body(request); const fields=['groupAttendedCount','groupNoShowCount','oneToOneAttendedCount','oneToOneNoShowCount','oneToOneTrialCount'];
      if(fields.some(field=>!Number.isInteger(d?.[field])||d[field]<0||d[field]>1000)||typeof d?.notes!=='string'||!d.notes.trim()||d.notes.length>5000||(d.evidenceUrl!==undefined&&(typeof d.evidenceUrl!=='string'||d.evidenceUrl.length>2000)))return json({error:'All class counts must be whole numbers from 0–1000 and a short work summary is required.'},400);
      const existing=await env.DB.prepare('SELECT id,status FROM salary_report_submissions WHERE cycle_id=? AND teacher_id=?').bind(cycle.id,teacher.id).first();
      if(existing&&existing.status!=='rejected')return json({error:'A salary report already exists for this cycle. Finance must review it before it can change.'},409);
      const late=now().slice(0,10)>cycle.submission_due_on?1:0;
      const values=[d.groupAttendedCount,d.groupNoShowCount,d.oneToOneAttendedCount,d.oneToOneNoShowCount,d.oneToOneTrialCount,d.notes.trim(),d.evidenceUrl?.trim()||null,late,now()];
      if(existing) await env.DB.prepare("UPDATE salary_report_submissions SET group_attended_count=?,group_no_show_count=?,one_to_one_attended_count=?,one_to_one_no_show_count=?,one_to_one_trial_count=?,notes=?,evidence_url=?,submitted_late=?,status='submitted',submitted_at=?,reviewed_by_user_id=NULL,reviewed_at=NULL,review_note=NULL,updated_at=? WHERE id=?").bind(...values,now(),existing.id).run();
      else await env.DB.prepare('INSERT INTO salary_report_submissions (id,cycle_id,teacher_id,group_attended_count,group_no_show_count,one_to_one_attended_count,one_to_one_no_show_count,one_to_one_trial_count,notes,evidence_url,submitted_late,status,submitted_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,\'submitted\',?,?)').bind(id(),cycle.id,teacher.id,...values,now()).run();
      await audit(env,user,'salary_report.submitted','pay_cycle',cycle.id,{teacherId:teacher.id,late:Boolean(late),resubmission:Boolean(existing)});
      return json({ok:true,resubmission:Boolean(existing),submittedLate:Boolean(late)},existing?200:201);
    }
    const salaryReview=url.pathname.match(/^\/api\/salary-reports\/([^/]+)$/);
    if (salaryReview && request.method === 'PATCH') {
      if(!can(user,'admin','finance'))return forbidden();
      const d=await body(request); if(!['approved','rejected','paid'].includes(d?.status)||(d.reviewNote!==undefined&&(typeof d.reviewNote!=='string'||d.reviewNote.length>5000)))return json({error:'A valid review status and optional short review note are required.'},400);
      const report=await env.DB.prepare('SELECT id,status,cycle_id FROM salary_report_submissions WHERE id=?').bind(salaryReview[1]).first(); if(!report)return json({error:'Salary report not found.'},404);
      const allowed={submitted:['approved','rejected'],approved:['paid'],rejected:[],paid:[]}; if(!allowed[report.status].includes(d.status))return json({error:`Cannot move a ${report.status} salary report to ${d.status}.`},409);
      await env.DB.prepare('UPDATE salary_report_submissions SET status=?,reviewed_by_user_id=?,reviewed_at=?,review_note=?,updated_at=? WHERE id=?').bind(d.status,user.id,now(),d.reviewNote?.trim()||null,now(),report.id).run();
      await audit(env,user,'salary_report.reviewed','salary_report',report.id,{from:report.status,to:d.status,cycleId:report.cycle_id}); return json({ok:true});
    }
    if (url.pathname === '/api/pay-cycles' && request.method === 'GET') { if(!can(user,'admin','finance','academics','lss','teacher'))return forbidden(); const cycles=await env.DB.prepare('SELECT id,starts_on,ends_on,submission_due_on,status FROM pay_cycles ORDER BY starts_on DESC LIMIT 24').all(); return json({cycles:cycles.results}); }
    if (url.pathname === '/api/pay-cycles' && request.method === 'POST') { if(!can(user,'admin','finance','academics'))return forbidden(); const d=await body(request); if(!isValidHalfMonthCycle(d?.startsOn,d?.endsOn))return json({error:'A cycle must be the 1st–15th or 16th–last day of one month.'},400); const policy=env.PAYMENT_DEADLINE_POLICY==='legacy_announcement'?'legacy_announcement':'two_calendar_days'; const cycle={id:id(),startsOn:d.startsOn,endsOn:d.endsOn,dueOn:cycleDueDate(d.endsOn,policy),deadlinePolicy:policy}; await env.DB.prepare('INSERT INTO pay_cycles (id,starts_on,ends_on,submission_due_on) VALUES (?,?,?,?)').bind(cycle.id,cycle.startsOn,cycle.endsOn,cycle.dueOn).run(); await audit(env,user,'pay_cycle.created','pay_cycle',cycle.id,{deadlinePolicy:policy}); return json({cycle},201); }
    const payCycle = url.pathname.match(/^\/api\/pay-cycles\/([^/]+)$/);
    if (payCycle && request.method === 'PATCH') { if(!can(user,'admin','finance','academics'))return forbidden(); const d=await body(request); if(!['open','review','approved','paid','closed'].includes(d?.status))return json({error:'A valid cycle status is required.'},400); const cycle=await env.DB.prepare('SELECT id,status FROM pay_cycles WHERE id=?').bind(payCycle[1]).first(); if(!cycle)return json({error:'Payment cycle not found.'},404); const allowed={open:['review'],review:['approved','open'],approved:['paid','review'],paid:['closed'],closed:[]}; if(!allowed[cycle.status].includes(d.status))return json({error:`Cannot move a ${cycle.status} cycle to ${d.status}.`},409); await env.DB.prepare('UPDATE pay_cycles SET status=? WHERE id=?').bind(d.status,cycle.id).run(); await audit(env,user,'pay_cycle.status_updated','pay_cycle',cycle.id,{from:cycle.status,to:d.status}); return json({ok:true}); }
    if (url.pathname === '/api/academic-dates' && request.method === 'GET') { const from=url.searchParams.get('from')||'2026-08-01'; const to=url.searchParams.get('to')||'2027-07-01'; if(!validDate(from)||!validDate(to)||from>to)return json({error:'from and to must be valid ISO dates.'},400); const dates=await env.DB.prepare('SELECT id,title,starts_on,ends_on,category,is_no_class,source FROM academic_dates WHERE starts_on<=? AND ends_on>=? ORDER BY starts_on,ends_on,title').bind(to,from).all(); return json({dates:dates.results}); }
    if (url.pathname === '/api/incidents' && request.method === 'GET') { const own=user.role==='teacher'; const incidents=await env.DB.prepare(`SELECT i.id,i.group_id,i.kind,i.learning_mode,i.occurred_at,i.waited_minutes,i.details,i.status,i.lss_notified_at,i.resolution,i.created_at,i.updated_at,g.name AS group_name FROM operational_incidents i LEFT JOIN groups g ON g.id=i.group_id ${own?'WHERE i.reporter_user_id=?':''} ORDER BY i.occurred_at DESC LIMIT 200`).bind(...(own?[user.id]:[])).all(); return json({incidents:incidents.results}); }
    if (url.pathname === '/api/incidents' && request.method === 'POST') { if(!can(user,'admin','academics','lss','teacher'))return forbidden(); const d=await body(request); const mode=d?.learningMode||'unknown'; if(!incidentKinds.has(d?.kind)||!learningModes.has(mode)||!validDateTime(d?.occurredAt)||typeof d?.details!=='string'||!d.details.trim()|| (d.waitedMinutes!==undefined&&(!Number.isInteger(d.waitedMinutes)||d.waitedMinutes<0)))return json({error:'kind, learningMode, occurredAt, details and an optional non-negative waitedMinutes are required.'},400); const minimumWait=mode==='group'?20:mode==='one_to_one'?15:0; if(d.kind==='class_no_show'&&Number(d.waitedMinutes||0)<minimumWait)return json({error:`A ${mode==='group'?'group':'one-to-one'} no-show report requires at least ${minimumWait} waited minutes.`},409); if(user.role==='teacher'&&d.groupId){const teacher=await teacherForUser(env,user.id); const assignment=teacher&&await env.DB.prepare('SELECT 1 AS assigned FROM teacher_groups WHERE teacher_id=? AND group_id=?').bind(teacher.id,d.groupId).first(); if(!assignment)return forbidden();} const incident={id:id(),reporterUserId:user.id,groupId:d.groupId||null,kind:d.kind,learningMode:mode,occurredAt:d.occurredAt,waitedMinutes:d.waitedMinutes??null,details:d.details.trim()}; await env.DB.prepare('INSERT INTO operational_incidents (id,reporter_user_id,group_id,kind,learning_mode,occurred_at,waited_minutes,details) VALUES (?,?,?,?,?,?,?,?)').bind(incident.id,incident.reporterUserId,incident.groupId,incident.kind,incident.learningMode,incident.occurredAt,incident.waitedMinutes,incident.details).run(); await audit(env,user,'incident.created','operational_incident',incident.id,{kind:incident.kind,learningMode:incident.learningMode}); return json({incident:{...incident,status:'open'}},201); }
    const incidentRoute=url.pathname.match(/^\/api\/incidents\/([^/]+)$/);
    if (incidentRoute && request.method === 'PATCH') { if(!can(user,'admin','academics','lss'))return forbidden(); const d=await body(request); if(!['open','escalated','resolved'].includes(d?.status))return json({error:'A valid incident status is required.'},400); if(d.resolution!==undefined&&(typeof d.resolution!=='string'||d.resolution.length>5000))return json({error:'resolution must be a short text value.'},400); const incident=await env.DB.prepare('SELECT id FROM operational_incidents WHERE id=?').bind(incidentRoute[1]).first(); if(!incident)return json({error:'Incident not found.'},404); const lssAt=d.lssNotified===true?now():null; await env.DB.prepare('UPDATE operational_incidents SET status=?,lss_notified_at=coalesce(?,lss_notified_at),resolution=coalesce(?,resolution),updated_at=? WHERE id=?').bind(d.status,lssAt,d.resolution??null,now(),incident.id).run(); await audit(env,user,'incident.updated','operational_incident',incident.id,{status:d.status,lssNotified:Boolean(lssAt)}); return json({ok:true}); }
    if (url.pathname === '/api/calendar/events' && request.method === 'GET') { const own=user.role==='teacher'?await teacherForUser(env,user.id):null; const from=url.searchParams.get('from')||now(); const events=await env.DB.prepare(`SELECT e.*,g.name AS group_name FROM calendar_events e LEFT JOIN groups g ON g.id=e.group_id ${own?'JOIN teacher_groups tg ON tg.group_id=e.group_id WHERE tg.teacher_id=? AND e.starts_at>=?':'WHERE e.starts_at>=?'} ORDER BY e.starts_at LIMIT 100`).bind(...(own?[own.id,from]:[from])).all(); return json({events:events.results}); }
    if (url.pathname === '/api/calendar/events' && request.method === 'POST') { if(!can(user,'admin','academics','lss')) return forbidden(); const d=await body(request); if(!d?.title||!validDateTime(d.startsAt)||!validDateTime(d.endsAt)||new Date(d.startsAt)>=new Date(d.endsAt)) return json({error:'title plus valid start/end ISO date-times with a timezone are required.'},400); const event={id:id(),title:d.title,startsAt:d.startsAt,endsAt:d.endsAt,groupId:d.groupId||null,meetUrl:d.meetUrl||null}; await env.DB.prepare('INSERT INTO calendar_events (id,group_id,title,starts_at,ends_at,meet_url) VALUES (?,?,?,?,?,?)').bind(event.id,event.groupId,event.title,event.startsAt,event.endsAt,event.meetUrl).run(); await audit(env,user,'calendar_event.created','calendar_event',event.id); return json({event},201); }
    if (url.pathname === '/api/integrations/google' && request.method === 'GET') { if(!can(user,'admin','academics','lss'))return forbidden(); const setting=await env.DB.prepare("SELECT status,config_json,updated_at FROM integration_settings WHERE provider='google_workspace'").first(); if(!setting)return json({status:'not_connected'}); const config=JSON.parse(setting.config_json); return json({status:setting.status,calendarId:config.calendarId||null,connectedAccountEmail:config.connectedAccountEmail||null,scopes:config.scopes||[],updatedAt:setting.updated_at}); }
    if (url.pathname === '/api/integrations/google/calendar' && request.method === 'PUT') { if(!can(user,'admin'))return forbidden(); const d=await body(request); if(typeof d?.calendarId!=='string'||!d.calendarId.trim())return json({error:'A Google Calendar ID is required.'},400); const setting=await env.DB.prepare("SELECT config_json FROM integration_settings WHERE provider='google_workspace' AND status='connected'").first(); if(!setting)return json({error:'Connect Google Workspace before selecting a calendar.'},409); const config={...JSON.parse(setting.config_json),calendarId:d.calendarId.trim(),configuredAt:now()}; await env.DB.prepare("UPDATE integration_settings SET config_json=?,updated_at=? WHERE provider='google_workspace'").bind(JSON.stringify(config),now()).run(); await audit(env,user,'integration.google.calendar_configured','integration','google_workspace',{calendarId:config.calendarId}); return json({ok:true}); }
    const syncEvent = url.pathname.match(/^\/api\/calendar\/events\/([^/]+)\/sync$/);
    if (syncEvent && request.method === 'POST') { if(!can(user,'admin','academics','lss'))return forbidden(); const event=await env.DB.prepare('SELECT e.*,g.calendar_id AS group_calendar_id FROM calendar_events e LEFT JOIN groups g ON g.id=e.group_id WHERE e.id=?').bind(syncEvent[1]).first(); if(!event)return json({error:'Calendar event not found.'},404); if(event.google_event_id)return json({ok:true,googleEventId:event.google_event_id,meetUrl:event.meet_url,syncStatus:event.sync_status}); try { const {accessToken,config}=await googleAccessToken(env); const calendarId=event.group_calendar_id||config.calendarId; if(!calendarId) return json({error:'No Google Calendar has been configured for this event.'},409); const googleEvent={summary:event.title,start:{dateTime:event.starts_at},end:{dateTime:event.ends_at},conferenceData:{createRequest:{requestId:id(),conferenceSolutionKey:{type:'hangoutsMeet'}}}}; const response=await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events?conferenceDataVersion=1`,{method:'POST',headers:{authorization:`Bearer ${accessToken}`,'content-type':'application/json'},body:JSON.stringify(googleEvent)}); if(!response.ok)throw new Error(`Google Calendar insert failed (${response.status}).`); const created=await response.json(); const meetUrl=created.hangoutLink||created.conferenceData?.entryPoints?.find(point=>point.entryPointType==='video')?.uri||null; await env.DB.prepare("UPDATE calendar_events SET google_event_id=?,meet_url=coalesce(?,meet_url),sync_status='synced' WHERE id=?").bind(created.id,meetUrl,event.id).run(); await audit(env,user,'calendar_event.google_synced','calendar_event',event.id,{googleEventId:created.id}); return json({ok:true,googleEventId:created.id,meetUrl}); } catch(error) { await env.DB.prepare("UPDATE calendar_events SET sync_status='error' WHERE id=?").bind(event.id).run(); await audit(env,user,'calendar_event.google_sync_failed','calendar_event',event.id); return json({error:error.message||'Google Calendar synchronization failed.'},502); } }
    if (url.pathname === '/api/forms' && request.method === 'GET') { if(!can(user,'admin','academics','finance','lss'))return forbidden(); const mappings=await env.DB.prepare('SELECT id,google_form_id,label,purpose,status,last_response_at,created_at,updated_at FROM form_mappings ORDER BY label').all(); return json({mappings:mappings.results}); }
    if (url.pathname === '/api/forms' && request.method === 'POST') { if(!can(user,'admin','academics','finance','lss'))return forbidden(); const d=await body(request); if(!d?.googleFormId||!d?.label||!['payment_method','onboarding','feedback','attendance'].includes(d.purpose))return json({error:'googleFormId, label and a supported purpose are required.'},400); const mapping={id:id(),googleFormId:d.googleFormId.trim(),label:d.label.trim(),purpose:d.purpose,fieldMap:JSON.stringify(d.fieldMap||{})}; await env.DB.prepare('INSERT INTO form_mappings (id,google_form_id,label,purpose,field_map_json,created_by_user_id) VALUES (?,?,?,?,?,?)').bind(mapping.id,mapping.googleFormId,mapping.label,mapping.purpose,mapping.fieldMap,user.id).run(); await audit(env,user,'form_mapping.created','form_mapping',mapping.id,{purpose:mapping.purpose}); return json({mapping},201); }
    const formSync=url.pathname.match(/^\/api\/forms\/([^/]+)\/sync$/);
    if(formSync&&request.method==='POST') { if(!can(user,'admin','academics','finance','lss'))return forbidden(); const mapping=await env.DB.prepare("SELECT * FROM form_mappings WHERE id=? AND status='active'").bind(formSync[1]).first(); if(!mapping)return json({error:'An active form mapping was not found.'},404); try { const {accessToken}=await googleAccessToken(env); const params=new URLSearchParams({pageSize:'1000'}); if(mapping.last_response_at)params.set('filter',`timestamp > ${mapping.last_response_at}`); let pageToken=null; let responses=[]; do { if(pageToken)params.set('pageToken',pageToken); const response=await fetch(`https://forms.googleapis.com/v1/forms/${encodeURIComponent(mapping.google_form_id)}/responses?${params}`,{headers:{authorization:`Bearer ${accessToken}`}}); if(!response.ok)throw new Error(`Google Forms response import failed (${response.status}).`); const page=await response.json(); responses=responses.concat(page.responses||[]); pageToken=page.nextPageToken||null; } while(pageToken&&responses.length<5000); const imports=[]; let latest=mapping.last_response_at; for(const response of responses){const submitted=response.lastSubmittedTime||response.createTime||null; if(submitted&&(!latest||submitted>latest))latest=submitted; imports.push(env.DB.prepare('INSERT OR IGNORE INTO form_response_imports (id,mapping_id,google_response_id,submitted_at,encrypted_payload_json) VALUES (?,?,?,?,?)').bind(id(),mapping.id,response.responseId,submitted,JSON.stringify(await encryptSecret(JSON.stringify(response),env))));} if(imports.length)await env.DB.batch(imports); await env.DB.prepare('UPDATE form_mappings SET last_response_at=?,updated_at=? WHERE id=?').bind(latest||mapping.last_response_at,now(),mapping.id).run(); await audit(env,user,'form_mapping.synced','form_mapping',mapping.id,{responsesFetched:responses.length}); return json({ok:true,responsesFetched:responses.length,lastResponseAt:latest||null}); } catch(error) { await env.DB.prepare("UPDATE form_mappings SET status='error',updated_at=? WHERE id=?").bind(now(),mapping.id).run(); await audit(env,user,'form_mapping.sync_failed','form_mapping',mapping.id); return json({error:error.message||'Google Forms synchronization failed.'},502); } }
    if (url.pathname === '/api/integrations/google/start' && request.method === 'GET') { if(!can(user,'admin')) return forbidden(); if(!env.GOOGLE_CLIENT_ID||!env.GOOGLE_REDIRECT_URI) return json({error:'Google OAuth is not configured.'},503); const state=await sign({sub:user.id,exp:Date.now()+10*60*1000,purpose:'google-oauth'},env); const params=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:env.GOOGLE_REDIRECT_URI,response_type:'code',access_type:'offline',prompt:'consent',scope:'openid email https://www.googleapis.com/auth/calendar.events https://www.googleapis.com/auth/forms.body.readonly https://www.googleapis.com/auth/forms.responses.readonly https://www.googleapis.com/auth/drive.readonly',state}); return Response.redirect(`https://accounts.google.com/o/oauth2/v2/auth?${params}`,302); }
    return json({ error: 'Not found' }, 404);
  }
};
